version: '2'
services:

  verify:
    image: registry.jincor.com/backend/verify-develop:latest
    build:
        context: ./
        dockerfile: Dockerfile
    environment:
      REDIS_URL: 'redis://redis:6379'
      FORCE_HTTPS: disabled
      MAIL_DRIVER: dummy
    tty: true
    ports:
      - "3000"
      - "4000"
    volumes:
      - ./:/usr/src/app
    links:
      - redis

  redis:
    image: jincort/backend-redis:production
    ports:
      - "6379"
