version: '2'
services:

  verify:
    image: registry.jincor.com/backend/verify:latest
    build:
        context: ./
        dockerfile: Dockerfile.prod
    environment:
      REDIS_URL: 'redis://redis:6379'
      FORCE_HTTPS: disabled
      AUTH_API_URL: ${AUTH_API_URL}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAILGUN_SECRET: ${MAILGUN_SECRET}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
    ports:
      - "3000"
      - "4000"
    links:
      - redis

  redis:
    image: registry.jincor.com/backend/redis:latest
    ports:
      - "6379"
